server:
  port: 8084

database:
  driver: mysql
  host: 127.0.0.1
  # host: host.docker.internal
  port: 3306
  username: gotiny
  password: 123456
  dbname: gotiny
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  addr: 127.0.0.1:6379
  # addr: host.docker.internal:6379
  password: ""
  db: 0

jwt:
  secret: gotiny
  expire_hours: 720

rabbitmq:
  host: 127.0.0.1
  # host: host.docker.internal
  port: 5672
  username: guest
  password: guest
  queue: gotiny
  exchange: gotiny
  routing_key: gotiny
  exchange_type: direct
  durable: true
  auto_delete: false
  internal: false
  no_wait: false
  no_local: false
  max_retries: 0
  retry_delay: 0
  max_retry_delay: 0
  global: false
  delivery_mode: 2
  priority: 0
  content_type: text/plain
  content_encoding: utf-8
  correlation_id: ""
  reply_to: ""
  expiration: ""
  message_id: ""
  timestamp: ""
  type: ""
  user_id: ""
  app_id: ""
  cluster_id: ""
  headers: {}
  body: ""

