server:
  port: 8084

database:
  driver: mysql
  # host: 127.0.0.1
  host: host.docker.internal
  port: 3306
  username: gotiny
  password: 123456
  dbname: gotiny
  charset: utf8mb4
  parseTime: true
  loc: Local

redis:
  # addr: 127.0.0.1:6379
  addr: host.docker.internal:6379
  password: ""
  db: 0

jwt:
  secret: gotiny
  expire_hours: 720