version: '3.8'

services:
  app:
    build: .
    # image: wucenglou/go-tiny:v1.0.1
    container_name: go-tiny-app
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - db
      - redis
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./config.yaml:/app/go-tiny/config.yaml
    command: ["./server", "-c", "config.yaml"]

  db:
    image: mysql:8.0.21
    container_name: go-tiny-db
    restart: always
    command: mysqld --character_set_server=utf8mb4 --collation_server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "gotiny"
      MYSQL_USER: "gotiny"
      MYSQL_PASSWORD: "123456"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "gotiny", "-p123456"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6.0-alpine
    container_name: go-tiny-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./redis-data:/data

volumes:
  mysql-data:
  redis-data: